name: Quality Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Security Check
        run: npm audit
        continue-on-error: true

      - name: Run Tests & Coverage
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: "demo"
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "demo"
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: "demo"
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "demo"
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "demo"
          NEXT_PUBLIC_FIREBASE_APP_ID: "demo"
          GOOGLE_APPLICATION_CREDENTIALS: "demo"
          GOOGLE_CLOUD_PROJECT_ID: "demo"
          GOOGLE_CLOUD_CLIENT_EMAIL: "demo"
          GOOGLE_CLOUD_PRIVATE_KEY: "demo"
        run: npm test -- --coverage --maxWorkers=50%  --max-old-space-size=4096

      - name: Run Linting
        run: npm run lint

      - name: Check Formatting
        run: npx prettier --check .

      - name: prisma generate
        run: npx prisma generate

      - name: build app
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          GOOGLE_CLOUD_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLOUD_CLIENT_EMAIL }}
          GOOGLE_CLOUD_PRIVATE_KEY: ${{ secrets.GOOGLE_CLOUD_PRIVATE_KEY }}
        run: |
          echo "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}"
          echo "${{ vars.GOOGLE_CLOUD_CLIENT_EMAIL }}"
          echo "${{ vars.GOOGLE_CLOUD_PROJECT_ID }}"
          echo "$GOOGLE_CLOUD_PROJECT_ID"
          npm run build

      - name: Check Spelling
        run: npx cspell lint "**" --gitignore

      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'
